[package]
name = "run_bevy_tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.1"
serde = "1.0"
rand = "0.8"
# bevy-inspector-egui = "0.9"